### ISSUE TITLE
Identify all breakpoints we'll use

### ISSUE THREAD

**Issue by mindrones** [nestauk/eurito_indicators#7]

**Comment by saabi** [comment]
After gauging screen dimensions in 'glyph units' across 301 devices and configurations thanks to Browserstack (and my UHD TV), we determined the best fitting layout breakpoints to have a band-size of 45 characters per line.

This leaves 4 breakpoints at 45, 90, 135 and 180 and 5 bands at:
 * XS:  [0, 45)
 * S: [45, 90)
 * M: [90, 135)
 * L: [135, 180)
 * XL: [180, ∞)

Below is the full range of devices including one UHD TV display at full screen on Chrome (the outlier).
![image](https://user-images.githubusercontent.com/1522062/110013397-55ed0200-7d00-11eb-8da3-619282397088.png)

The same chart without the TV to offer more detail on the majority of devices.
![image](https://user-images.githubusercontent.com/1522062/110014552-b16bbf80-7d01-11eb-8ca5-e402aa26fb3e.png)

In both charts dot size is the device pixel ratio and:
 * Blue: Android
 * Red: iOS
 * Orange: Windows
 * Green: OS X
